# Generated by Django 6.0.7 on 2026-08-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='deadline',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='project',
            name='stakeholders',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
